sudo: false
language: rust
cache:
  - cargo

script:
  - cargo build --verbose
  - cargo test --verbose

before_deploy:
  - cargo doc --verbose
  - echo '<meta http_equiv="refresh" content="0; url=ray_tracing_in_a_weekend/index.html" />' > target/doc/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  local_dir: target/doc
  on:
    branch: master
